name: mytrainer2client
description: "A Flutter Project That Serves as a Client for Keycloak + Spring Boot."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.3.0
  url_strategy: ^0.2.0
  openid_client: ^0.4.9            # web
  flutter_appauth: ^6.0.2          # mobile (>=6 fixes namespace issue)
  flutter_secure_storage: ^9.0.0   # mobile
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  avatar_plus: ^0.0.5
  table_calendar: ^3.1.1
  collection: ^1.18.0
  dropdown_search: ^5.0.5      # searchable single & multi select
  multi_select_flutter: ^4.1.3 # chip-style multi select

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # REQUIRED so that l10n.yaml is honored
  generate: true

  uses-material-design: true



  assets:
    - assets/landing_page_background.png
